apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gotthard.componentName" (dict "root" . "component" "postgres") }}
  labels: {{- include "gotthard.labels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.postgres.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
