apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotthard.componentName" (dict "root" . "component" "frontend") }}
  labels: {{- include "gotthard.labels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector: {{- include "gotthard.selectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
