apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotthard.componentName" (dict "root" . "component" "postgres") }}
  labels: {{- include "gotthard.labels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "gotthard.selectorLabels" (dict "root" . "component" "postgres") | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
