-- gotthard-spring — policy corpus seed (RAG knowledge base, spec item 4).
--
-- Text only. `embedding` is left NULL here on purpose: a chunk's vector is a derived
-- artefact of its text *and* the embedding algorithm, not a fact about the world, and
-- hand- (or script-) written 384-dimensional literals for ~50 chunks would both bloat
-- this migration and risk drifting out of step with whatever EmbeddingModel produced
-- them if that model ever changed. ch.gotthard.ai.retrieval.PolicyCorpusEmbeddingInitializer
-- computes and writes every chunk's embedding at application startup instead, from the
-- exact same EmbeddingModel bean PgVectorKnowledgeRetriever embeds queries with — see its
-- Javadoc for the full reasoning. That split is this project's answer to "seed via
-- V3__seed_policy_corpus.sql or a startup loader": both, each for the half it suits —
-- text is declarative and reviewable like V2's operator seed, embeddings are code because
-- they are computed, not authored.
--
-- The rows below are every "## N. Section" chunk of every document in docs/policy/,
-- in document order, generated by applying ai.retrieval.MarkdownPolicyChunker's exact
-- parsing convention by hand (see that class's Javadoc for the shape it expects, and
-- MarkdownPolicyChunkerTest for the convention exercised as a real test). chunk_id is a
-- UUIDv5 of "DOCUMENT#SECTION" against a fixed namespace, so regenerating this file from
-- an unchanged corpus reproduces the same ids.
--
-- Every document is written for this exercise and says so on its own first page — see
-- docs/policy/README.md. None of this is, or reproduces, any real institution's policy.

-- 54 chunks across 9 documents

INSERT INTO policy_chunks (chunk_id, document, title, section, body, metadata) VALUES
    ('bf7a93cb-b780-551c-afce-5bd1f8916a43', 'AML-001', 'Purpose and scope', '1', 'This document tells an operator what structuring looks like in customer activity, and
what the console''s automated detection (rule `R-01`) means when it fires. It applies to
card, payment and crypto activity alike — structuring is a behaviour, not a channel, and
a customer who cannot split cash deposits will happily split card loads or transfers
instead.', '{}'),
    ('d0da4c2a-f82e-50d6-8ff9-54b1c9bc9a2d', 'AML-001', 'Definitions', '2', '**Structuring** (also called smurfing) is breaking one transaction that would trigger a
reporting obligation into several smaller ones that individually would not. **Near-threshold**
describes an amount placed just under the reporting line on purpose — not
CHF 4''000, but CHF 9''700, CHF 9''850, CHF 9''900. A single near-threshold payment proves
nothing; a pattern of them does.', '{}'),
    ('9859f823-dbb9-5923-ad6b-f77723698509', 'AML-001', 'Detection criteria', '3', '`R-01` fires when a customer places three or more near-threshold amounts within a
rolling seven-day window, and those amounts aggregate to CHF 10''000 or more across the
same window. Both conditions are required: three small amounts that never add up to
anything is a customer who transacts often, and one large aggregate reached through a
single payment is simply a large payment. It is the count and the total together that
describe someone managing around a line they know exists.', '{}'),
    ('ca9c5d56-8a4a-5609-83d6-349cce2465b9', 'AML-001', 'Typical patterns', '4', '- Three transfers of CHF 9''500, CHF 9''600 and CHF 9''800 to the same beneficiary inside
  four days.
- A sequence of card loads that creeps upward in count during a single week, each one
  comfortably under the threshold on its own.
- Round-number amounts that cluster just below CHF 10''000 rather than being spread
  randomly the way ordinary spending is.', '{}'),
    ('a84f6981-f6d0-5f6a-8766-3669f2d31acd', 'AML-001', 'Operator actions', '5', 'Read the transaction list behind the finding before doing anything else — the pattern
should be visible in the numbers, not just asserted by the score. Request the customer''s
own explanation and supporting documentation for the underlying purpose of the funds
(invoice, contract, source of funds). Do not tell the customer that transactions under a
specific amount avoid reporting — that framing is itself a customer-care outcome
attracts unwanted scrutiny, and confirming the exact threshold to a customer defeats the
control. See `SOP-01` for what may be said and done without a supervisor.', '{}'),
    ('cb40642b-4743-521e-8d9e-71b5adf2b486', 'AML-001', 'Escalation and reporting', '6', 'A confirmed structuring pattern is escalated to a supervisor the same business day.
Where the aggregate reaches CHF 10''000 or more with no credible business explanation,
file an Internal Escalation Report per `SOP-01` §6 regardless of the account''s prior
history — a clean record is not a defence against a pattern seen in the current window.', '{}'),
    ('887412cc-ef8d-5239-baac-efd700c1cf11', 'AML-002', 'Purpose and scope', '1', 'This document covers accounts that go quiet for a long stretch and then transact
heavily in a short window, and what the console''s automated detection (rule `R-06`)
means when it fires. It applies to card, payment and crypto activity alike — dormancy
followed by a burst is a behaviour of the account, not of any one channel.', '{}'),
    ('736b7d55-5f30-5c0c-a90d-7a00a696b573', 'AML-002', 'Definitions', '2', '**Dormancy** is an extended stretch with no transaction activity at all — not merely
quiet, but silent. A **burst** is a cluster of several transactions inside a single day
immediately following that silence. Neither half is remarkable alone: dormancy on its
own describes a customer on sabbatical, travelling, or simply not needing the account
for a while, and a busy day on its own describes an ordinary customer having a busy day.
It is the two together, dormancy immediately followed by a burst, that is worth an
operator''s attention.', '{}'),
    ('2fa150b5-1b73-5eee-96ae-6500ac052962', 'AML-002', 'Detection criteria', '3', '`R-06` fires when an account with at least ninety days of continuous silence records
five or more transactions within the following twenty-four hours. The channel does not
matter for either half of the pattern — the ninety days of silence and the five
transactions can each be any mix of card, payment and crypto activity.', '{}'),
    ('74d23896-8bdc-5959-b933-9b4e2203db53', 'AML-002', 'Typical patterns', '4', '- An account with no activity for several months that suddenly moves money out across
  several transactions in the same day, consistent with a takeover rather than the
  legitimate owner''s return.
- A dormant account that reactivates with a burst of small transactions that look like
  testing whether the account still functions, followed by larger ones.
- Reactivation that coincides with a change to the customer''s contact details or
  credentials shortly beforehand — worth checking even though it sits outside this
  rule''s own criteria.', '{}'),
    ('4c918d82-6921-5311-9c13-bca42d409343', 'AML-002', 'Operator actions', '5', 'Contact the customer through a verified channel — not one supplied during the burst
itself — to confirm they, and not someone who has taken over the account, are behind
the activity. Request an explanation for both the dormancy and the reactivation; a
credible one (return from travel, a life event, resuming a business) closes the matter
without further action. Where the customer cannot be reached or does not recognise the
activity, a temporary hold on further transactions is within an operator''s own authority
per `SOP-01` §3.', '{}'),
    ('5874decc-7c9e-520e-b2a2-933c5bf1e6e8', 'AML-002', 'Escalation and reporting', '6', 'Escalate to a supervisor the same business day whenever the customer cannot be reached
or does not recognise the reactivation. File an Internal Escalation Report per `SOP-01`
§6 wherever account takeover cannot be ruled out, since a taken-over account is both a
fraud loss and a potential money-laundering channel at once.', '{}'),
    ('f3063875-f75d-5342-9d0d-b921b94c15b4', 'AML-003', 'Purpose and scope', '1', 'This document covers card spend concentrated at merchant categories that sit closest to
cash, and what the console''s automated detection (rule `R-07`) means when it fires. It
applies to the card channel.', '{}'),
    ('6137eee4-a01b-5837-a728-acd3e83211f6', 'AML-003', 'Definitions', '2', 'A **merchant category code (MCC)** classifies what kind of business a card
transaction was made at. **Quasi-cash** merchants are ones that sell instruments
readily converted back to cash — money orders, prepaid cards, casino chips, some
cryptocurrency kiosks. **Money-transfer** merchants are wire and remittance services.
**Gambling** merchants sit alongside these because gambling losses and winnings are
themselves a well-known way to give illicit funds a legitimate-looking origin. Together
these three categories are the ones where a card purchase comes closest to simply
withdrawing cash, which is why concentration in them specifically is the signal, not
card spend in general.', '{}'),
    ('2fe85fa5-9ea4-52ea-97c4-13e1eeb676e0', 'AML-003', 'Detection criteria', '3', '`R-07` fires when a customer''s card spend at quasi-cash, money-transfer and gambling
MCCs together reaches CHF 2''500 or more within a rolling twenty-four-hour window. Which
individual MCCs count toward the total is a data question answered by the query behind
the rule, not by this document; this document only explains what crossing the total
means.', '{}'),
    ('f3539afa-2290-56d0-b456-8eef9b5014e0', 'AML-003', 'Typical patterns', '4', '- Several purchases at money-order or prepaid-card outlets on the same day, each
  individually unremarkable.
- A concentrated run of gambling-merchant transactions that does not match the
  customer''s typical spend pattern.
- Quasi-cash spend that immediately follows a large incoming payment, consistent with
  converting it back toward cash quickly.', '{}'),
    ('a867b16c-e48d-57b4-817f-d03d7692e4e4', 'AML-003', 'Operator actions', '5', 'Compare the day''s concentration against the customer''s ordinary spending pattern before
treating it as remarkable — a customer who regularly uses money-transfer services to
support family abroad is not exhibiting new behaviour just because a threshold sums it
up in one day. Request an explanation where the concentration is new or inconsistent
with the customer''s profile. A credible explanation (a one-off large remittance, a
casino visit) closes the matter without further action.', '{}'),
    ('7c57a9cf-6dbf-5834-a311-f2014ebe4f0e', 'AML-003', 'Escalation and reporting', '6', 'Escalate to a supervisor the same business day where the concentration repeats across
multiple days or where no credible explanation is offered. File an Internal Escalation
Report per `SOP-01` §6 wherever quasi-cash concentration follows shortly after a
near-threshold or structuring finding under `AML-001` — the combination is a stronger
signal than either alone.', '{}'),
    ('89e8b787-771b-53c8-b20d-7cfcdd85b1bb', 'CRYPTO-01', 'Purpose and scope', '1', 'This document covers crypto that arrives in a customer''s wallet and is moved straight on
to an exchange, and what the console''s automated detection (rule `R-04`) means when it
fires. It applies to the crypto channel. Wallet-graph proximity to a specifically flagged
address is a related but distinct pattern, covered separately in `CRYPTO-02`.', '{}'),
    ('33dc3881-fde1-5525-bf2b-f1939971ad00', 'CRYPTO-01', 'Definitions', '2', '**Rapid disposal** is crypto sent on to an exchange wallet very soon after arriving —
minutes or a small number of hours, rather than the days or weeks an investor typically
holds a position. **Layering** is moving value through a chain of wallets or services
specifically to obscure its origin before it reaches a point where it converts back to
fiat currency; an exchange deposit is usually that point, which is what makes the speed
of arrival-to-deposit meaningful.', '{}'),
    ('96f80477-d9cd-5197-9591-e65c221b481c', 'CRYPTO-01', 'Detection criteria', '3', '`R-04` fires when funds arrive in a wallet and are sent on to a recognised exchange
within one hour, and the wallet''s total outbound volume over the same rolling
twenty-four-hour window reaches CHF 10''000 or more (converted at the recorded rate).
Neither half is remarkable alone — wallets legitimately receive funds, and wallets
legitimately pay exchanges to cash out — it is the combination of speed and size that
distinguishes a pass-through wallet from an investor''s own holdings.', '{}'),
    ('94c7fbf3-50c2-5ffb-8380-520835a9a933', 'CRYPTO-01', 'Typical patterns', '4', '- A wallet that has no other activity, receives a transfer, and forwards nearly the
  whole amount to an exchange within minutes.
- A sequence of wallets each holding funds only briefly before passing them one hop
  closer to an exchange — a chain rather than a single hop.
- Deposit timing that clusters immediately after arrival regardless of market
  conditions, which is not how an investor timing a sale behaves.', '{}'),
    ('1d30e449-4a0d-577c-9247-d8376c917eb1', 'CRYPTO-01', 'Operator actions', '5', 'Review the wallet''s transaction history for the window, not just the single flagged
transfer — a genuine one-off cash-out looks different from a wallet used repeatedly this
way. Request the customer''s explanation for the source of the incoming funds and the
reason for immediate disposal. A single rapid disposal with a credible, documented
source (a sale of a personal holding, a payment received in crypto for goods or
services) does not by itself require a freeze.', '{}'),
    ('0b53c8d4-f71c-53b4-8689-a1cfcde73faa', 'CRYPTO-01', 'Escalation and reporting', '6', 'Escalate to a supervisor the same business day whenever the source of funds cannot be
explained or documented. File an Internal Escalation Report per `SOP-01` §6 where rapid
disposal repeats across multiple windows, or where the receiving exchange is itself
poorly regulated or previously associated with other escalations — cross-reference
`CRYPTO-02` when the wallet''s counterpart is a mixer rather than a plain exchange.', '{}'),
    ('3017edaa-b425-5624-b1da-8a7b2d72eac8', 'CRYPTO-02', 'Purpose and scope', '1', 'This document covers exposure to wallets on the firm''s watch list through the
blockchain''s own transaction graph, and what the console''s automated detection
(rule `R-05`) means when it fires. It applies to the crypto channel. Rapid movement of
funds into a plain exchange is a related but distinct pattern, covered separately in
`CRYPTO-01`.', '{}'),
    ('8a1acb2a-781b-513d-8ef4-86b7ffc163d7', 'CRYPTO-02', 'Definitions', '2', 'A **flagged wallet** is an address the firm''s watch list associates with sanctioned
actors, ransomware, theft, darknet markets or a **mixer** (also called a tumbler) — a
service designed specifically to break the link between a deposit and a withdrawal by
pooling many users'' funds together. A **hop** is one transaction distance in the
blockchain''s transaction graph: a wallet that pays a flagged address directly is at hop
one; a wallet that pays a wallet that pays a flagged address is at hop two, and so on.
**Wallet clustering** is the practice of grouping addresses that transaction patterns
suggest are controlled by the same actor, which is how proximity is measured
meaningfully rather than address-by-address.', '{}'),
    ('a52ef57a-35fe-5ab8-863c-14a4279f4ca1', 'CRYPTO-02', 'Detection criteria', '3', '`R-05` fires when a depth-limited walk of the wallet transaction graph finds a flagged
address within two hops of the wallet under review. Distance carries the whole signal:
paying a flagged address directly, or receiving directly from one, scores at full
weight; a single intermediary wallet between the two — one hop further out — scores at
half weight. Anything beyond two hops, or unreachable within the search depth, does not
fire the rule at all, since at that distance the graph connects almost every wallet to
almost every other one and the signal stops meaning anything.', '{}'),
    ('a64dc1e8-88b9-5da3-af5f-f296c5f0d383', 'CRYPTO-02', 'Typical patterns', '4', '- A direct transfer to or from an address the watch list already carries.
- A single pass through one intermediary wallet on the way to or from a flagged
  address — the classic use of a "peel chain" to add distance.
- Funds routed through a service the watch list identifies as a mixer, after which the
  destination address itself may look entirely unremarkable.', '{}'),
    ('e3f02b66-91b8-5b77-a811-97e146e1485a', 'CRYPTO-02', 'Operator actions', '5', 'Review how many hops separate the customer''s wallet from the flagged address before
deciding how urgently to act — a direct transfer warrants faster handling than a single
intermediary hop. Request the customer''s explanation for the counterparty relationship.
Do not assume guilt from proximity alone: a wallet can receive an unsolicited transfer
from anywhere, and an exchange''s own hot wallet can sit near a flagged address in the
graph purely through the exchange''s own volume.', '{}'),
    ('61aaa67a-fbd6-5478-a123-949d45a90cf7', 'CRYPTO-02', 'Escalation and reporting', '6', 'Escalate a direct (one-hop) match to a supervisor immediately; escalate a one-intermediary
(two-hop) match the same business day. File an Internal Escalation Report per `SOP-01` §6
for any confirmed direct exposure to a flagged address, and for a two-hop match once the
customer''s explanation has been reviewed and found insufficient.', '{}'),
    ('9bd69502-80a5-51c1-a14b-559786ce1c4a', 'FRAUD-01', 'Purpose and scope', '1', 'This document covers card-not-present (CNP) decline clusters and what the console''s
automated detection (rule `R-03`) means when it fires. It applies to the card channel
only. Unlike the AML documents in this corpus, the customer here is frequently the
victim, not the suspect — the card number is usually stolen, and the account holder may
not yet know it.', '{}'),
    ('9a0f257f-3aba-51db-b7d6-dfb854463dd6', 'FRAUD-01', 'Definitions', '2', '**Card-not-present** means the physical card was never presented to a merchant terminal
— an online purchase, a phone order, a stored-credential charge. **Card testing** is the
practice of running a small number of low-value, high-frequency authorisation attempts
across many merchants to find out whether a stolen card number, expiry date and security
code combination still works, before using it for a larger purchase elsewhere.', '{}'),
    ('239fe58a-88d1-549b-871e-576da872a45a', 'FRAUD-01', 'Detection criteria', '3', '`R-03` fires when a card accumulates three or more declined card-not-present
authorisation attempts within a rolling one-hour window, spread across two or more
distinct merchants. Both the decline count and the merchant spread are required: a
customer mistyping their own card details repeatedly at one merchant is a support
question, not a fraud pattern; the signature of testing is the same card failing
different merchants in quick succession.', '{}'),
    ('5143fe45-5726-56ed-88d2-9c7b39528195', 'FRAUD-01', 'Typical patterns', '4', '- A run of small-value declined attempts (often under CHF 5) at unrelated online
  merchants within a few minutes of each other.
- Authorisation attempts against merchant categories with weak or no address
  verification, tried one after another.
- A quiet card that suddenly generates a burst of CNP attempts with no purchase pattern
  resembling the customer''s history.', '{}'),
    ('9493d9bc-f617-5a11-9c83-853d836a1eb7', 'FRAUD-01', 'Operator actions', '5', 'Do not wait for a successful fraudulent charge to act — the value of catching a testing
pattern is acting before the tested number is used for real. Contact the customer
through a verified channel (not a channel supplied in the transaction itself) to confirm
whether they recognise the activity. Where the customer does not recognise it, a
temporary hold on the card pending reissue is within an operator''s own authority per
`SOP-01` §3; a full account freeze is not, and needs supervisor sign-off per `SOP-01` §4.', '{}'),
    ('29ce4240-97c2-5130-9027-10c7e3556f23', 'FRAUD-01', 'Escalation and reporting', '6', 'Escalate to a supervisor the same business day whenever the customer does not recognise
the activity, regardless of whether any attempt actually succeeded. File an Internal
Escalation Report per `SOP-01` §6 once a card has been confirmed compromised, so the
pattern is on record even though the customer is the victim rather than the subject of
suspicion.', '{}'),
    ('5dc3285e-7238-5c4d-a4b0-47d82f29d12d', 'GOV-01', 'Purpose and scope', '1', 'This document explains how the console''s risk rating works end to end, and how its
pieces are meant to relate to each other. Where the other documents in this corpus
explain one detection pattern each, this one explains the frame all of them sit inside:
the rating scale, the roles that act on it, and what to do when two independent
assessments of the same activity disagree.', '{}'),
    ('2988eba2-db5d-58a0-a7c6-09ef58b31371', 'GOV-01', 'Risk rating framework', '2', 'Every assessed transaction and customer window carries a numeric score from nought to a
hundred, which resolves to one of four bands. A score opens a band at the point shown
and holds it up to the next band''s threshold:

| Level | Opens at | What it means |
|---|---|---|
| LOW | 0 | Nothing notable fired. Ordinary activity. |
| MEDIUM | 25 | At least one lower-weighted pattern fired, or several together. |
| HIGH | 50 | A serious pattern fired, or several moderate ones compounded. |
| CRITICAL | 75 | Multiple serious patterns, or one pattern at its most severe. |

The exact weight each pattern contributes is tunable data, not fixed in this document —
see `GOV-01` §3 for why, and consult the console''s own rule configuration for current
values.', '{}'),
    ('15ec3e44-8e1a-54be-afab-fddb86262c46', 'GOV-01', 'How detection and the assistant''s analysis relate', '3', 'The console''s automated rules compute the score and the level from §2 directly from
transaction data — deterministically, the same input always produces the same output,
and every rule that fires is written to the audit trail. **The rules decide the level;
nothing else does.** An AI assistant separately reviews the same window and produces its
own written summary, proposed actions, and its own independent assessed level. The
assistant''s assessed level is recorded alongside the computed level, not instead of it,
and the two are never silently reconciled into one number.

**When the computed level and the assessed level diverge, that divergence is itself a
signal worth an operator''s attention** — not a bug to be resolved by picking one over
the other. A lower assessed level than computed may mean the rules caught something
genuinely explainable by context the assistant could see in the narrative; a higher
assessed level than computed may mean the assistant noticed something the rules were
never written to catch. Either way, see `SOP-01` §6: a divergence is grounds for an
Internal Escalation Report on its own.', '{}'),
    ('04985fc1-67e6-5cb5-ac87-8d87b6c2f4e8', 'GOV-01', 'Roles and responsibilities', '4', 'See `SOP-01` §2 for the operator and supervisor roles and what each may do. This
document adds only the program-level point: supervisors are additionally responsible for
keeping rule weights current as patterns evolve, and for the quality of filed Internal
Escalation Reports, not only for individual case decisions.', '{}'),
    ('9ee3064c-d141-55a7-b462-974e3fad9271', 'GOV-01', 'Escalation matrix', '5', 'See `SOP-01` §5 for the operator-facing timing table. At the program level: CRITICAL
findings are reviewed in aggregate weekly regardless of individual case outcomes, to
catch patterns that recur across customers rather than within one customer''s history.', '{}'),
    ('584a4cfc-ec26-52fe-a309-d32b8178d153', 'GOV-01', 'Review, audit trail and this document''s own limits', '6', 'Every rule that fires writes an audit row; every AI analysis records what policy text it
was shown and how well each chunk matched, so a later reviewer can see exactly what
grounded a given write-up. This corpus of nine documents is deliberately short and was
written for a take-home exercise — it is illustrative of how a real policy layer would
be structured and retrieved, not a substitute for one. A real deployment would replace
every document here with the firm''s actual, current, legally reviewed policy text, and
would keep it current through a real governance cycle rather than a single commit.', '{}'),
    ('660c00db-a15c-5226-a7ea-cbdcb7210d88', 'SANCTIONS-01', 'Purpose and scope', '1', 'This document covers cross-border payments whose beneficiary bank sits in a
jurisdiction the firm treats as elevated risk, and what the console''s automated
detection (rule `R-02`) means when it fires. It applies to the payment channel only —
card and crypto cross-border exposure are covered by `FRAUD-01` and `CRYPTO-01`/`CRYPTO-02`
respectively, since the risk indicators differ by rail.', '{}'),
    ('8bc3c691-1926-5562-bf4b-19e68a99862b', 'SANCTIONS-01', 'Definitions', '2', 'An **elevated-risk jurisdiction** is a country on the firm''s maintained watch list —
standing in for the kind of list a real compliance function tracks against FATF
guidance and similar sources, updated on a policy cycle rather than hard-coded into any
one document. A **corridor** is a repeated or sizeable flow of payments toward the same
elevated-risk destination, as distinct from a single transfer, which is simply a fact
about a customer''s life (family abroad, an overseas supplier, a property purchase).', '{}'),
    ('f7f9fb48-3712-5339-8e9e-c2a9953bbc98', 'SANCTIONS-01', 'Detection criteria', '3', '`R-02` fires when a payment reaches a beneficiary bank in an elevated-risk jurisdiction
and either of two conditions also holds: two or more such cross-border transfers within
a rolling seven-day window, or a single week''s cross-border volume to that jurisdiction
of CHF 5''000 or more. A single small transfer to a listed country, on its own, does not
fire the rule — the corridor is what matters, not the destination alone.', '{}'),
    ('e132693f-3d24-5ff8-85d8-5e53f0536271', 'SANCTIONS-01', 'Typical patterns', '4', '- Weekly transfers to the same beneficiary account in an elevated-risk country that
  individually look unremarkable but repeat every cycle.
- A sudden first-time transfer of size to a jurisdiction the customer has no apparent
  connection to in their onboarding profile.
- Multiple small transfers to different beneficiaries that all resolve to banks in the
  same elevated-risk country within a short window.', '{}'),
    ('cc6f957c-53f2-5bc7-8170-3f1ac052ed0d', 'SANCTIONS-01', 'Operator actions', '5', 'Check whether the destination is consistent with the customer''s declared profile —
family, business, property, employment — before assuming the worst; a corridor to a
country of birth or prior residence is common and often benign. Where the purpose is not
already on file, request supporting documentation for the transfer (invoice, contract,
relationship evidence). A single elevated-risk transfer with a credible, documented
purpose does not need escalation; a repeating corridor does, whether or not a purpose
has been offered.', '{}'),
    ('460b7161-8e8c-5f0c-951c-0b79f5f7c156', 'SANCTIONS-01', 'Escalation and reporting', '6', 'Escalate a confirmed corridor to a supervisor the same business day. Where the customer
cannot or will not explain the purpose of a repeating elevated-risk corridor, file an
Internal Escalation Report per `SOP-01` §6. Do not disclose to the customer that a
specific country triggered review — describe the request as routine documentation only,
per `SOP-01` §6''s no-tipping-off rule.', '{}'),
    ('8688accd-15dc-5f7e-9379-93d8021f441d', 'SOP-01', 'Purpose and scope', '1', 'This document is the single reference for what a customer-care operator using the
console may do when a customer''s activity is flagged, at any risk level and for any of
the patterns described elsewhere in this corpus. Where a topic-specific document
(`AML-001` through `CRYPTO-02`) gives pattern-specific guidance, it points back here for
what an operator is actually authorised to do; this document is where that authority is
defined once.', '{}'),
    ('9163816e-69d7-5f29-9cb2-57c8e6b8803b', 'SOP-01', 'Roles', '2', 'The console recognises two operator roles. An **operator** handles day-to-day review:
reading activity, requesting documents, placing a temporary hold, and escalating. A
**supervisor** holds everything an operator holds, plus the authority to freeze an
account fully, close or dismiss an escalated case, and lift a hold or a freeze. A
finding never requires action beyond an operator''s own authority to be looked at — only
certain actions require a supervisor.', '{}'),
    ('86da8ffc-99ad-57bb-86aa-5b0030d6671a', 'SOP-01', 'What an operator may do without escalation', '3', '- **Request documents.** Ask the customer for supporting evidence — proof of funds,
  an invoice, a contract, identification — through the standard document request flow.
- **Ask clarifying questions.** Contact the customer through a verified channel to ask
  about a specific transaction or pattern.
- **Review.** Read the customer''s full activity history and any AI-generated analysis
  in the console; reviewing is never itself an action that needs authorisation.
- **Place a temporary hold on a single transaction.** Pause one pending transaction
  while documentation is gathered. This is not the same as freezing the account, and
  does not require supervisor sign-off.
- **Note the case file.** Record findings, correspondence and reasoning against the
  customer''s record for the audit trail.', '{}'),
    ('2dd0dde9-26b3-5215-8bd8-36d5d41503e6', 'SOP-01', 'What requires supervisor sign-off', '4', '- **Freezing an account.** Stopping all activity on an account, as opposed to holding
  one transaction, is a supervisor decision.
- **Unfreezing or lifting a hold.** Only a supervisor reverses either action, even the
  operator who placed it.
- **Dismissing a HIGH or CRITICAL finding.** An operator may close a LOW or MEDIUM
  finding with a documented, credible explanation; HIGH and CRITICAL findings are closed
  by a supervisor only.
- **Filing an Internal Escalation Report.** An operator prepares the report; a
  supervisor reviews and files it (§6).', '{}'),
    ('3f3e036b-796b-5b47-afac-4d857b2d262e', 'SOP-01', 'Escalation triggers by risk level', '5', '| Level | Operator action | Timing |
|---|---|---|
| LOW | Note the file. No customer contact required unless curious. | — |
| MEDIUM | Review within two business days; may request documents. | 2 business days |
| HIGH | Escalate to a supervisor; consider a temporary hold. | Same business day |
| CRITICAL | Escalate to a supervisor immediately; hold pending review. | Immediately |', '{}'),
    ('7b418b0f-ff65-5325-a185-3fd768f479b3', 'SOP-01', 'Filing an Internal Escalation Report', '6', 'Where a topic document directs it, or where the console''s computed level and the AI
assistant''s own assessed level diverge, prepare an **Internal Escalation Report (IER)**
— this corpus''s fictional stand-in for the kind of internal suspicion report a real
compliance function would file. An IER records: the customer reference, the activity
window reviewed, the rule codes that fired, the AI assistant''s summary, and the
operator''s own notes and any customer response obtained. A supervisor reviews and files
it; an operator never files one unreviewed.

**Never tell a customer they are the subject of an escalation or a report.** Disclosing
that fact is called tipping off, and it can destroy the value of a review in progress
even when the underlying activity turns out to be entirely legitimate. Document requests
and clarifying questions are always framed as routine.', '{}');
